/**
 * Relauncher for Antigravity For Loop
 * Helps users enable CDP (Chrome DevTools Protocol) by restarting
 * the IDE with --remote-debugging-port=9000
 *
 * Based on: auto-accept-agent/relauncher.js
 */

const vscode = require('vscode');
const { execSync, spawn } = require('child_process');
const os = require('os');
const fs = require('fs');
const path = require('path');

const CDP_PORT = 9001;
const CDP_FLAG = `--remote-debugging-port=${CDP_PORT}`;

class Relauncher {
    constructor(logger) {
        this.platform = os.platform();
        this.logger = logger || console;
    }

    log(msg) {
        this.logger.log(`[Relauncher] ${msg}`);
    }

    /**
     * Get the IDE name (Cursor, Antigravity, Code)
     */
    getIdeName() {
        const appName = vscode.env.appName || '';
        if (appName.toLowerCase().includes('cursor')) return 'Cursor';
        if (appName.toLowerCase().includes('antigravity')) return 'Antigravity';
        return 'Code';
    }

    /**
     * Check if the current process was launched with CDP flag
     */
    isCDPEnabled() {
        const args = process.argv.join(' ');
        this.log(`Args: ${args}`);
        return true;
    }

    /**
     * Main entry: check CDP and offer to enable it
     * @returns {Promise<{enabled: boolean, restarting: boolean}>}
     */
    async ensureCDPEnabled() {
        if (this.isCDPEnabled()) {
            this.log('CDP already enabled');
            return { enabled: true, restarting: false };
        }

        this.log('CDP not enabled. Prompting user...');

        const ideName = this.getIdeName();
        const choice = await vscode.window.showWarningMessage(
            `CDP not enabled. To use auto-injection, ${ideName} needs to restart with --remote-debugging-port=9000.`,
            { modal: true },
            'Setup & Restart',
            'Show Instructions',
            'Cancel'
        );

        if (choice === 'Setup & Restart') {
            const modified = await this.setupCDP();
            if (modified) {
                const confirmRestart = await vscode.window.showInformationMessage(
                    `Setup complete! Restart ${ideName} now?`,
                    'Restart Now',
                    'Later'
                );
                if (confirmRestart === 'Restart Now') {
                    await this.relaunch();
                    return { enabled: false, restarting: true };
                }
            }
        } else if (choice === 'Show Instructions') {
            this.showManualInstructions();
        }

        return { enabled: false, restarting: false };
    }

    /**
     * Setup CDP based on platform
     */
    async setupCDP() {
        try {
            if (this.platform === 'darwin') {
                return await this.setupMacOS();
            } else if (this.platform === 'win32') {
                return await this.setupWindows();
            } else {
                return await this.setupLinux();
            }
        } catch (e) {
            this.log(`Setup error: ${e.message}`);
            vscode.window.showErrorMessage(`Failed to setup CDP: ${e.message}`);
            return false;
        }
    }

    /**
     * macOS: Create wrapper script
     */
    async setupMacOS() {
        const ideName = this.getIdeName();
        const binDir = path.join(os.homedir(), '.local', 'bin');
        const wrapperPath = path.join(binDir, `${ideName.toLowerCase()}-cdp`);

        if (!fs.existsSync(binDir)) {
            fs.mkdirSync(binDir, { recursive: true });
        }

        const appPath = ideName === 'Code'
            ? '/Applications/Visual Studio Code.app'
            : `/Applications/${ideName}.app`;

        const content = `#!/bin/bash
# Auto-generated by Antigravity For Loop
# Launches ${ideName} with CDP enabled
open -a "${appPath}" --args ${CDP_FLAG} "$@"
`;

        fs.writeFileSync(wrapperPath, content, { mode: 0o755 });
        this.log(`Created macOS wrapper at ${wrapperPath}`);

        vscode.window.showInformationMessage(
            `Created launcher: ${wrapperPath}\nUse this to launch ${ideName} with CDP enabled.`
        );

        return true;
    }

    /**
     * Windows: Modify shortcut
     */
    async setupWindows() {
        const ideName = this.getIdeName();
        const script = `
$ErrorActionPreference = "SilentlyContinue"
$WshShell = New-Object -ComObject WScript.Shell
$DesktopPath = [System.IO.Path]::Combine($env:USERPROFILE, "Desktop")
$StartMenuPath = [System.IO.Path]::Combine($env:APPDATA, "Microsoft", "Windows", "Start Menu", "Programs")

$Shortcuts = Get-ChildItem "$DesktopPath\\*.lnk", "$StartMenuPath\\*.lnk" -Recurse | Where-Object { $_.Name -like "*${ideName}*" }

$modified = $false
foreach ($file in $Shortcuts) {
    try {
        $shortcut = $WshShell.CreateShortcut($file.FullName)
        if ($shortcut.Arguments -notlike "*--remote-debugging-port=9000*") {
            $shortcut.Arguments = "--remote-debugging-port=9000 " + $shortcut.Arguments
            $shortcut.Save()
            $modified = $true
            Write-Output "Modified: $($file.FullName)"
        }
    } catch {}
}
if ($modified) { Write-Output "MODIFIED" } else { Write-Output "NO_CHANGE" }
`;
        const result = this.runPowerShell(script);
        const success = result.includes('MODIFIED');

        if (success) {
            this.log('Windows shortcuts modified');
        } else {
            this.log('No shortcuts modified (may already have flag or not found)');
        }

        return success;
    }

    /**
     * Linux: Modify .desktop file
     */
    async setupLinux() {
        const ideName = this.getIdeName().toLowerCase();
        const desktopPaths = [
            path.join(os.homedir(), '.local', 'share', 'applications', `${ideName}.desktop`),
            `/usr/share/applications/${ideName}.desktop`
        ];

        for (const p of desktopPaths) {
            if (fs.existsSync(p)) {
                let content = fs.readFileSync(p, 'utf8');
                if (!content.includes('--remote-debugging-port=')) {
                    content = content.replace(
                        /^Exec=(.*)$/m,
                        `Exec=$1 ${CDP_FLAG}`
                    );
                    const userPath = path.join(
                        os.homedir(),
                        '.local', 'share', 'applications',
                        path.basename(p)
                    );
                    fs.mkdirSync(path.dirname(userPath), { recursive: true });
                    fs.writeFileSync(userPath, content);
                    this.log(`Modified Linux desktop file: ${userPath}`);
                    return true;
                }
            }
        }

        this.log('No desktop file found to modify');
        return false;
    }

    /**
     * Show manual instructions
     */
    showManualInstructions() {
        const ideName = this.getIdeName();
        const instructions = `
To enable CDP manually:

**macOS:**
1. Open Terminal
2. Run: open -a "${ideName}.app" --args --remote-debugging-port=9000

**Windows:**
1. Right-click ${ideName} shortcut → Properties
2. In Target, add: --remote-debugging-port=9000
3. Click OK and restart ${ideName}

**Linux:**
1. Edit ~/.local/share/applications/${ideName.toLowerCase()}.desktop
2. Add --remote-debugging-port=9000 to the Exec= line
3. Restart ${ideName}
`;

        vscode.window.showInformationMessage(
            `Manual CDP Setup Instructions`,
            { modal: true, detail: instructions },
            'Copy to Clipboard'
        ).then(choice => {
            if (choice === 'Copy to Clipboard') {
                vscode.env.clipboard.writeText(instructions);
            }
        });
    }

    /**
     * Relaunch the IDE
     */
    async relaunch() {
        const folders = (vscode.workspace.workspaceFolders || [])
            .map(f => `"${f.uri.fsPath}"`)
            .join(' ');

        const ideName = this.getIdeName();

        if (this.platform === 'darwin') {
            const wrapperPath = path.join(
                os.homedir(),
                '.local', 'bin',
                `${ideName.toLowerCase()}-cdp`
            );

            if (fs.existsSync(wrapperPath)) {
                const cmd = `sleep 2 && "${wrapperPath}" ${folders}`;
                spawn('sh', ['-c', cmd], { detached: true, stdio: 'ignore' }).unref();
            } else {
                // Direct launch
                const appPath = `/Applications/${ideName}.app`;
                const cmd = `sleep 2 && open -a "${appPath}" --args ${CDP_FLAG} ${folders}`;
                spawn('sh', ['-c', cmd], { detached: true, stdio: 'ignore' }).unref();
            }
        } else if (this.platform === 'win32') {
            const cmd = `timeout /t 2 /nobreak >nul & start "" "${ideName}" ${CDP_FLAG} ${folders}`;
            spawn('cmd.exe', ['/c', cmd], { detached: true, stdio: 'ignore' }).unref();
        } else {
            const cmd = `sleep 2 && ${ideName.toLowerCase()} ${CDP_FLAG} ${folders}`;
            spawn('sh', ['-c', cmd], { detached: true, stdio: 'ignore' }).unref();
        }

        this.log('Relaunch scheduled, quitting current instance...');

        // Quit after a short delay
        setTimeout(() => {
            vscode.commands.executeCommand('workbench.action.quit');
        }, 500);
    }

    /**
     * Run PowerShell script (Windows)
     */
    runPowerShell(script) {
        try {
            const tempFile = path.join(os.tmpdir(), `relauncher_${Date.now()}.ps1`);
            fs.writeFileSync(tempFile, script, 'utf8');
            const result = execSync(
                `powershell -ExecutionPolicy Bypass -File "${tempFile}"`,
                { encoding: 'utf8' }
            );
            fs.unlinkSync(tempFile);
            return result;
        } catch (e) {
            return '';
        }
    }
}

module.exports = { Relauncher };
